import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import lottie from 'lottie-web'
import { createRef, useEffect } from 'react'


export default function Home() {

  let animationContainer = createRef();

  useEffect(() => {
    const anim = lottie.loadAnimation({
        container: animationContainer.current,
        rerender: "svg",
        loop: true,
        autoplay: true,
        path: "/animations/data.json"
    })

    return () => anim.destroy();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.animation__container} ref={animationContainer}/>
      </main>
    </>
  )
}
